// Generated by https://quicktype.io

export interface Pokemons {
  count: number;
  next: string;
  previous: null;
  results: ResultPokemon[];
}

export interface ResultPokemon {
  name: string;
  url: string;
  type: Types[];
}

// Generated by https://quicktype.io

export interface Types {
  slot: number;
  type: Type;
}

export interface Type {
  name: string;
  url: string;
}
